version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.1.0
  aws-cli: circleci/aws-cli@3.1
  maven: circleci/maven@1.0.3

jobs:
  build:
    docker:
      - image: cimg/openjdk:16.0.0
    steps:
      - checkout
      #- maven/install
      #- aws-cli/install
      - run : mvn -version
      - run:
          name: Build A Package For AWS Device Farm
          command: clean package -DskipTests=true
      - run:
          name: Add POS to Dependency Zip
          command: zip -u target/zip-with-dependencies.zip */test/resources/POS.apk
      - run:
          name: Save Test Results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - run:
          name: Compress Artifacts
          command: tar -cvzf gradle-test-report.tar .*/build/reports/tests/test/
      - store_artifacts:
          path: gradle-test-report.tar
          destination: gradle-test-report.tar
#Nonsense
workflows:
  circle-ci-to-aws-device-farm-workflow:
    jobs:
      - build