version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:8.0.362
    environment:
      PROJECT_NAME: "Jenkins Appium Device Farm"
      DEVICE_POOL: "Samsung Galaxy Tab S8"
    steps:
      - checkout
      - run:
          name: Install CLI
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
      - run:
          name: Install Json Query (jq)
          command: sudo apt-get install jq
      - run:
          name: Building the deploy package for AWS Device Farm
          command: mvn clean package -DskipTests=true
      - run:
          name: Adding POS.apk to deploy package
          command: zip -u target/zip-with-dependencies.zip */test/resources/POS.apk
      - run:
          name: Configuring AWS Credentials
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set default.region us-west-2
      - run:
          name: Deploying code to AWS Device Farm
          command: |            
            export PROJECT_ARN=$(aws devicefarm list-projects | jq -r '.projects[] | select(.name == "'"$PROJECT_NAME"'") | .arn')
            echo "Project ARN: $PROJECT_ARN"
            
            export DEVICE_POOL_ARN=$(aws devicefarm list-device-pools --arn "$PROJECT_ARN" | jq -r '.devicePools[] | select(.name == "'"$DEVICE_POOL"'") | .arn')
            echo "Device Pool ARN: $DEVICE_POOL_ARN"            
            
            export APP_NAME="KDS-""$CIRCLE_BUILD_NUM"+".apk"      
            export APP_UPLOAD_RESPONSE=$(aws devicefarm create-upload --project-arn "$PROJECT_ARN" --name "$APP_NAME" --type ANDROID_APP)
            export APP_UPLOAD_URL=$(echo $APP_UPLOAD_RESPONSE | jq -r '.upload.url')
            export APP_UPLOAD_ARN=$(echo $APP_UPLOAD_RESPONSE | jq -r '.upload.arn')
            echo "App Upload ARN: $APP_UPLOAD_ARN"
            echo "App Upload URL: $APP_UPLOAD_URL"
            curl -T **/test/resources/KDS.apk "$APP_UPLOAD_URL"
            sleep 15
            export APP_UPLOAD_RESPONSE=$(aws devicefarm get-upload --arn "$APP_UPLOAD_ARN")
            echo "App Upload Status: $(echo $APP_UPLOAD_RESPONSE | jq -r '.upload.status')"
            
            export TEST_UPLOAD_RESPONSE=$(aws devicefarm create-upload --project-arn "$PROJECT_ARN" --name zip-with-dependencies.zip --type APPIUM_JAVA_TESTNG_TEST_PACKAGE)
            export TEST_UPLOAD_URL=$(echo $TEST_UPLOAD_RESPONSE | jq -r '.upload.url')
            export TEST_UPLOAD_ARN=$(echo $TEST_UPLOAD_RESPONSE | jq -r '.upload.arn')
            echo "Tests Upload ARN: $TEST_UPLOAD_ARN"
            echo "Tests Upload URL: $TEST_UPLOAD_URL"
            curl -T target/zip-with-dependencies.zip "$TEST_UPLOAD_URL"
            sleep 15
            export TEST_UPLOAD_RESPONSE=$(aws devicefarm get-upload --arn "$TEST_UPLOAD_ARN")
            echo "Test Upload Status: $(echo $TEST_UPLOAD_RESPONSE | jq -r '.upload.status')"
            
            export TEST_SPEC_UPLOAD_RESPONSE=$(aws devicefarm create-upload --name TraySpec.yml --type APPIUM_JAVA_TESTNG_TEST_SPEC --project-arn "$PROJECT_ARN")
            export TEST_SPEC_URL=$(echo $TEST_SPEC_UPLOAD_RESPONSE | jq -r '.upload.url')
            export TEST_SPEC_ARN=$(echo $TEST_SPEC_UPLOAD_RESPONSE | jq -r '.upload.arn')
            echo "Tests Spec ARN: $TEST_SPEC_ARN"
            echo "Tests Spec URL: $TEST_SPEC_URL"
            curl -T **/test/resources/TraySpec.yml "$TEST_SPEC_URL"
            sleep 15
            export TEST_SPEC_UPLOAD_RESPONSE=$(aws devicefarm get-upload --arn "$TEST_SPEC_ARN")
            echo "Test Upload Status: $(echo $TEST_SPEC_UPLOAD_RESPONSE | jq -r '.upload.status')"
            
            export TEST_NAME="From-Circle-CI-""$CIRCLE_BUILD_NUM"                        
            export TEST_RUN_RESPONSE=$(aws devicefarm schedule-run --project-arn "$PROJECT_ARN" --app-arn "$APP_UPLOAD_ARN" --device-pool-arn $DEVICE_POOL_ARN --name "$TEST_NAME" --test testSpecArn="$TEST_SPEC_ARN",type=APPIUM_JAVA_TESTNG,testPackageArn="$TEST_UPLOAD_ARN")
            export TEST_RUN_STATUS=$(echo $TEST_RUN_RESPONSE | jq -r '.run.status')
            export TEST_RUN_ARN=$(echo $TEST_RUN_RESPONSE | jq -r '.run.arn')
            echo "Test Run Status: $TEST_RUN_STATUS"
            aws devicefarm get-run --arn "$TEST_RUN_ARN"
            sleep 360            
            export ARTIFACTS_ARN=$(aws devicefarm list-artifacts --arn "$TEST_RUN_ARN" --type FILE | jq -r '.artifacts[] | select(.type == "'VIDEO'") | .arn')
            export ARTIFACTS_URL=$(aws devicefarm list-artifacts --arn "$TEST_RUN_ARN" --type FILE | jq -r '.artifacts[] | select(.type == "'VIDEO'") | .url')
            echo "Artifacts ARN: $ARTIFACTS_ARN"
            echo "Artifacts URL: $ARTIFACTS_URL"
            sleep 15       
            curl "$ARTIFACTS_URL" > Execution.mp4
      - store_artifacts:
          path: Execution.mp4
          destination: Execution-"$CIRCLE_BUILD_NUM".mp4

workflows:
  circle-ci-to-aws-device-farm-workflow:
    jobs:
      - build:
          context: aws-keys